# Generated by Django 4.1.4 on 2022-12-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
